---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fss-server-deployment
  labels:
    app: fss-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fss-server
  template:
    metadata:
      labels:
        app: fss-server
    spec:
      containers:
      - name: fss-server
        image: tyvek2zhang/fastapi-sqlmodel-starter:v1.1.1
        command: ["sh", "-c", "cd fss && alembic upgrade head && python apiserver.py"]
        ports:
        - containerPort: 9010
