"""empty message

Revision ID: 0ac6f6fb6c17
Revises: 6e8a42d6c13e
Create Date: 2025-08-03 21:50:38.685790

"""

# revision identifiers, used by Alembic.
revision = "0ac6f6fb6c17"
down_revision = "6e8a42d6c13e"
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
