"""empty message

Revision ID: 07b069d14db5
Revises:
Create Date: 2025-07-19 16:10:35.294094

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "07b069d14db5"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "menus",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column("name", sa.String(length=50), nullable=False, comment="名称"),
        sa.Column("icon", sa.String(length=100), nullable=True, comment="图标"),
        sa.Column(
            "permission",
            sa.String(length=100),
            nullable=True,
            comment="权限标识",
        ),
        sa.Column("sort", sa.Integer(), nullable=True, comment="排序"),
        sa.Column(
            "path", sa.String(length=200), nullable=True, comment="路由地址"
        ),
        sa.Column(
            "component",
            sa.String(length=255),
            nullable=True,
            comment="组件路径",
        ),
        sa.Column(
            "type",
            sa.Integer(),
            nullable=True,
            comment="类型（1目录 2菜单 3按钮）",
        ),
        sa.Column(
            "cacheable",
            sa.Integer(),
            nullable=True,
            comment="是否缓存（1缓存 0不缓存）",
        ),
        sa.Column(
            "visible",
            sa.Integer(),
            nullable=True,
            comment="是否显示（1显示 0隐藏）",
        ),
        sa.Column("parent_id", sa.Integer(), nullable=True, comment="父ID"),
        sa.Column(
            "status", sa.Integer(), nullable=True, comment="状态（1正常 0停用）"
        ),
        sa.Column(
            "create_time", sa.DateTime(), nullable=True, comment="创建时间"
        ),
        sa.Column(
            "update_time", sa.DateTime(), nullable=True, comment="更新时间"
        ),
        sa.Column(
            "comment", sa.String(length=500), nullable=True, comment="备注信息"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name", name="udx_name"),
        comment="系统菜单表",
    )
    op.create_index("idx_parent_id", "menus", ["parent_id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column(
            "username", sa.String(length=32), nullable=False, comment="用户名"
        ),
        sa.Column(
            "password", sa.String(length=64), nullable=False, comment="密码"
        ),
        sa.Column(
            "nickname", sa.String(length=32), nullable=False, comment="昵称"
        ),
        sa.Column(
            "avatar_url",
            sa.String(length=64),
            nullable=True,
            comment="头像地址",
        ),
        sa.Column(
            "status",
            sa.Integer(),
            nullable=True,
            comment="状态(0:停用,1:待审核,2:正常,3:已注销)",
        ),
        sa.Column(
            "remark", sa.String(length=255), nullable=True, comment="备注"
        ),
        sa.Column(
            "create_time", sa.DateTime(), nullable=True, comment="创建时间"
        ),
        sa.Column(
            "update_time", sa.DateTime(), nullable=True, comment="更新时间"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("username", name="ix_sys_user_username"),
        comment="用户信息表",
    )
    op.execute("""
        INSERT INTO users (id, username, password, nickname, avatar_url, status, remark, create_time, update_time) VALUES(9, 'admin', '$2b$12$qupycbom77r6MoRuCW5L8um0QUmCazQgBNfv4otYwX3nnXP55dVg6', '管理员', NULL, 1, '管理员', '2025-05-21 22:18:22.868513', '2025-05-21 22:18:22.868513');
    """)

    op.execute("""
        INSERT INTO `menus` VALUES (1, '系统管理', 'Settings', NULL, 2, '/system', NULL, 1, NULL, 1, 0, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `menus` VALUES (5, '工具箱', 'Wrench', NULL, 8, '/tool', NULL, 1, NULL, 1, 0, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `menus` VALUES (12, '用户管理', 'Users', NULL, 1, '/system/user', NULL, 2, NULL, 1, 1, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `menus` VALUES (14, '菜单管理', 'Menu', NULL, 3, '/system/menu', NULL, 2, NULL, 1, 1, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `menus` VALUES (15, '角色管理', 'UserCog', NULL, 4, '/system/role', NULL, 2, NULL, 1, 1, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `menus` VALUES (17, '代码生成', 'Code2', NULL, 2, '/tool/code', NULL, 2, NULL, 1, 5, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `menus` VALUES (19, '系统监控', 'Activity', NULL, 10, '/monitor', NULL, 1, NULL, 1, 0, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `menus` VALUES (20, '异常页面', 'Bug', NULL, 11, '/exception', NULL, 1, NULL, 0, 0, NULL, NULL, NULL, NULL);
    """)
    op.execute("""
        INSERT INTO `menus` VALUES (24, '首页', 'Home', NULL, 1, '/home', NULL, 1, NULL, 1, 0, NULL, NULL, NULL, NULL);
    """)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("users")
    op.drop_index("idx_parent_id", table_name="menus")
    op.drop_table("menus")
    # ### end Alembic commands ###
