"""empty message

Revision ID: f79c82a40367
Revises: f8a553993d86
Create Date: 2025-07-28 21:53:16.326126

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'f79c82a40367'
down_revision = 'f8a553993d86'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table_comment(
        'db_databases',
        '数据库信息表',
        existing_comment=None,
        schema=None
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table_comment(
        'db_databases',
        existing_comment='数据库信息表',
        schema=None
    )
    # ### end Alembic commands ###
