"""empty message

Revision ID: 6e8a42d6c13e
Revises: b9c28e86a4a6
Create Date: 2025-08-03 19:26:51.328804

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "6e8a42d6c13e"
down_revision = "b9c28e86a4a6"
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "dict_data",
        sa.Column("id", sa.BigInteger(), nullable=False, comment="主键"),
        sa.Column("sort", sa.Integer(), nullable=True, comment="字典排序"),
        sa.Column("label", sa.String(length=64), nullable=True, comment="字典标签"),
        sa.Column("value", sa.String(length=64), nullable=True, comment="字典键值"),
        sa.Column("type", sa.String(length=64), nullable=True, comment="字典类型"),
        sa.Column("echo_style", sa.String(length=64), nullable=True, comment="回显样式"),
        sa.Column("ext_class", sa.String(length=64), nullable=True, comment="扩展样式"),
        sa.Column("is_default", sa.Integer(), nullable=True, comment="是否默认(1是 0否)"),
        sa.Column("status", sa.Integer(), nullable=True, comment="状态(1正常 0停用)"),
        sa.Column("comment", sa.String(length=255), nullable=True, comment="备注"),
        sa.Column("create_time", sa.DateTime(), nullable=True, comment="创建时间"),
        sa.Column("update_time", sa.DateTime(), nullable=True, comment="更新时间"),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("dict_data")
    # ### end Alembic commands ###
