"""empty message

Revision ID: d907907bc6b3
Revises: 07b069d14db5
Create Date: 2025-07-29 17:32:11.059804

"""
from alembic import op
import sqlalchemy as sa
import sqlmodel # added


# revision identifiers, used by Alembic.
revision = 'd907907bc6b3'
down_revision = '07b069d14db5'
branch_labels = None
depends_on = None


def upgrade():
    # op.execute("CREATE EXTENSION IF NOT EXISTS pg_trgm")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('db_connections',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('connection_name', sa.String(length=32), nullable=False, comment='连接名称'),
    sa.Column('database_type', sa.String(length=16), nullable=False, comment='数据库类型'),
    sa.Column('connection_database', sa.String(length=64), nullable=True, comment='连接数据库名称'),
    sa.Column('host', sa.String(length=16), nullable=True, comment='主机'),
    sa.Column('port', sa.Integer(), nullable=True, comment='端口号'),
    sa.Column('username', sa.String(length=32), nullable=True, comment='用户名'),
    sa.Column('password', sa.String(length=64), nullable=True, comment='密码'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='连接信息表'
    )
    op.create_table('db_databases',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('connection_id', sa.BigInteger(), nullable=False, comment='数据库连接id'),
    sa.Column('database_name', sa.String(length=64), nullable=False, comment='数据库名称'),
    sa.Column('owner', sa.String(length=64), nullable=True, comment='拥有者'),
    sa.Column('template', sa.String(length=64), nullable=True, comment='使用模板'),
    sa.Column('encoding', sa.String(length=32), nullable=True, comment='字符编码'),
    sa.Column('collation_order', sa.String(length=32), nullable=True, comment='排序规则'),
    sa.Column('character_classification', sa.String(length=32), nullable=True, comment='字符分类'),
    sa.Column('tablespace', sa.String(length=64), nullable=True, comment='表空间名称'),
    sa.Column('connection_limit', sa.Integer(), nullable=True, comment='连接限制'),
    sa.Column('allow_connection', sa.Boolean(), nullable=True, comment='是否允许连接'),
    sa.Column('is_template', sa.Boolean(), nullable=True, comment='是否为模板数据库'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='数据库信息表'
    )
    op.create_index('ix_db_database_connection_id', 'db_databases', ['connection_id'], unique=False)
    op.create_index(op.f('ix_db_databases_connection_id'), 'db_databases', ['connection_id'], unique=False)
    op.create_table('db_indexes',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('table_id', sa.BigInteger(), nullable=False, comment='表id'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='索引名称'),
    sa.Column('field', sa.String(length=64), nullable=False, comment='索引字段'),
    sa.Column('type', sa.String(length=16), nullable=False, comment='索引类型'),
    sa.Column('remark', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='索引信息表'
    )
    op.create_table('db_meta_fields',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('table_id', sa.BigInteger(), nullable=False, comment='表id'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='字段名称'),
    sa.Column('type', sa.String(length=32), nullable=False, comment='字段类型'),
    sa.Column('length', sa.Integer(), nullable=True, comment='总长度'),
    sa.Column('scale', sa.Integer(), nullable=True, comment='小数长度'),
    sa.Column('default', sa.String(length=64), nullable=True, comment='默认值'),
    sa.Column('comment', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('nullable', sa.SmallInteger(), nullable=True, comment='允许为空(0否,1是)'),
    sa.Column('primary_key', sa.SmallInteger(), nullable=True, comment='主键(0否,1是)'),
    sa.Column('autoincrement', sa.SmallInteger(), nullable=True, comment='自增(0否,1是)'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='字段信息表'
    )
    op.create_index(op.f('ix_db_meta_fields_table_id'), 'db_meta_fields', ['table_id'], unique=False)
    op.create_table('db_meta_tables',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('database_id', sa.BigInteger(), nullable=False, comment='数据库id'),
    sa.Column('name', sa.String(length=64), nullable=False, comment='表名称'),
    sa.Column('comment', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='表结构信息'
    )
    op.create_index(op.f('ix_db_meta_tables_database_id'), 'db_meta_tables', ['database_id'], unique=False)
    op.create_table('gen_fields',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('db_table_id', sa.BigInteger(), nullable=False, comment='数据库表ID'),
    sa.Column('db_field_id', sa.BigInteger(), nullable=False, comment='数据库字段ID'),
    sa.Column('field_name', sa.String(length=64), nullable=True, comment='字段名称'),
    sa.Column('field_type', sa.String(length=64), nullable=True, comment='字段类型'),
    sa.Column('sql_model_type', sa.String(length=64), nullable=True, comment='模型类型'),
    sa.Column('length', sa.Integer(), nullable=True, comment='字段长度'),
    sa.Column('scale', sa.Integer(), nullable=True, comment='分数位'),
    sa.Column('js_type', sa.String(length=64), nullable=True, comment='JS类型'),
    sa.Column('sort', sa.Integer(), nullable=True, comment='排序'),
    sa.Column('default', sa.String(length=64), nullable=True, comment='默认值'),
    sa.Column('primary_key', sa.SmallInteger(), nullable=True, comment='是否主键(0否,1是)'),
    sa.Column('nullable', sa.SmallInteger(), nullable=True, comment='允许为空(0否,1是)'),
    sa.Column('creatable', sa.SmallInteger(), nullable=True, comment='创建字段(0否,1是)'),
    sa.Column('queryable', sa.SmallInteger(), nullable=True, comment='查询字段(0否,1是)'),
    sa.Column('critical', sa.SmallInteger(), nullable=True, comment='列表字段(0否,1是)'),
    sa.Column('detailable', sa.SmallInteger(), nullable=True, comment='详情字段(0否,1是)'),
    sa.Column('updatable', sa.SmallInteger(), nullable=True, comment='修改字段(0否,1是)'),
    sa.Column('batch_updatable', sa.SmallInteger(), nullable=True, comment='批量修改(0否,1是)'),
    sa.Column('query_type', sa.String(length=64), nullable=True, comment='查询方式（等于、不等于、大于、小于、范围）'),
    sa.Column('html_type', sa.String(length=64), nullable=True, comment='显示类型(文本框、文本域、下拉框、复选框、单选框、日期控件)'),
    sa.Column('dict_type', sa.String(length=64), nullable=True, comment='字典类型'),
    sa.Column('comment', sa.String(length=255), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='代码生成字段表'
    )
    op.create_index(op.f('ix_gen_fields_db_field_id'), 'gen_fields', ['db_field_id'], unique=False)
    op.create_index(op.f('ix_gen_fields_db_table_id'), 'gen_fields', ['db_table_id'], unique=False)
    op.create_table('gen_tables',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='主键'),
    sa.Column('database_id', sa.BigInteger(), nullable=False, comment='数据库ID'),
    sa.Column('db_table_id', sa.BigInteger(), nullable=False, comment='数据库表ID'),
    sa.Column('table_name', sa.String(length=64), nullable=True, comment='表名'),
    sa.Column('sub_table_name', sa.String(length=64), nullable=True, comment='关联子表的表名'),
    sa.Column('sub_table_fk_name', sa.String(length=64), nullable=True, comment='子表关联的外键名'),
    sa.Column('class_name', sa.String(length=64), nullable=True, comment='实体类名称'),
    sa.Column('backend', sa.String(length=16), nullable=True, comment='后端语言'),
    sa.Column('tpl_category', sa.String(length=64), nullable=True, comment='使用的模板（crud单表操作 tree树表操作）'),
    sa.Column('tpl_web_type', sa.String(length=32), nullable=True, comment='前端模板类型'),
    sa.Column('tpl_backend_type', sa.String(length=32), nullable=True, comment='后端模板类型'),
    sa.Column('package_name', sa.String(length=128), nullable=True, comment='生成包路径'),
    sa.Column('module_name', sa.String(length=32), nullable=True, comment='生成模块名'),
    sa.Column('business_name', sa.String(length=32), nullable=True, comment='生成业务名'),
    sa.Column('function_name', sa.String(length=32), nullable=True, comment='生成功能名'),
    sa.Column('function_author', sa.String(length=32), nullable=True, comment='生成功能作者'),
    sa.Column('gen_type', sa.String(length=1), nullable=True, comment='生成代码方式（0zip压缩包 1自定义路径）'),
    sa.Column('gen_path', sa.String(length=255), nullable=True, comment='生成路径（不填默认项目路径）'),
    sa.Column('options', sa.String(length=255), nullable=True, comment='其它生成选项'),
    sa.Column('comment', sa.String(length=64), nullable=True, comment='表描述'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='代码生成业务表'
    )
    op.create_index(op.f('ix_gen_tables_database_id'), 'gen_tables', ['database_id'], unique=False)
    op.create_index(op.f('ix_gen_tables_db_table_id'), 'gen_tables', ['db_table_id'], unique=False)
    op.create_table('role_menu',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='自增编号'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('menu_id', sa.BigInteger(), nullable=False, comment='菜单ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色和菜单关联表'
    )
    op.create_table('roles',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('name', sa.String(length=30), nullable=False, comment='角色名称'),
    sa.Column('code', sa.String(length=100), nullable=False, comment='角色权限字符串'),
    sa.Column('sort', sa.Integer(), nullable=False, comment='显示顺序'),
    sa.Column('data_scope', sa.Integer(), nullable=True, comment='数据范围（1：全部数据权限 2：自定数据权限 3：本部门数据权限 4：本部门及以下数据权限）'),
    sa.Column('data_scope_dept_ids', sa.String(length=500), nullable=True, comment='数据范围(指定部门数组)'),
    sa.Column('status', sa.Integer(), nullable=False, comment='角色状态（0正常 1停用）'),
    sa.Column('comment', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='角色信息表'
    )
    op.create_table('user_role',
    sa.Column('id', sa.BigInteger(), nullable=False, comment='自增编号'),
    sa.Column('user_id', sa.BigInteger(), nullable=False, comment='用户ID'),
    sa.Column('role_id', sa.BigInteger(), nullable=False, comment='角色ID'),
    sa.Column('create_time', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('update_time', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.PrimaryKeyConstraint('id'),
    comment='用户和角色关联表'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_role')
    op.drop_table('roles')
    op.drop_table('role_menu')
    op.drop_index(op.f('ix_gen_tables_db_table_id'), table_name='gen_tables')
    op.drop_index(op.f('ix_gen_tables_database_id'), table_name='gen_tables')
    op.drop_table('gen_tables')
    op.drop_index(op.f('ix_gen_fields_db_table_id'), table_name='gen_fields')
    op.drop_index(op.f('ix_gen_fields_db_field_id'), table_name='gen_fields')
    op.drop_table('gen_fields')
    op.drop_index(op.f('ix_db_meta_tables_database_id'), table_name='db_meta_tables')
    op.drop_table('db_meta_tables')
    op.drop_index(op.f('ix_db_meta_fields_table_id'), table_name='db_meta_fields')
    op.drop_table('db_meta_fields')
    op.drop_table('db_indexes')
    op.drop_index(op.f('ix_db_databases_connection_id'), table_name='db_databases')
    op.drop_index('ix_db_database_connection_id', table_name='db_databases')
    op.drop_table('db_databases')
    op.drop_table('db_connections')
    # ### end Alembic commands ###
