name: "⭐ Feature or enhancement request"
description: Provide supporting details for a feature in development
labels: kind/feature
body:
  - type: textarea
    id: feature
    attributes:
      label: What would you like to be added?
      description: |
        Please list out the detailed feature description
    validations:
      required: true

  - type: textarea
    id: reference
    attributes:
      label: Requirement reference?
    validations:
      required: true

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: |
        Please provide a clear and quantifiable completion indicator.
      value: |
        <details>

        </details>
    validations:
      required: true
