version: '3.8'

services:
  # The postgres database.
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      # The password for the default postgres user.
      POSTGRES_PASSWORD: fss123#456
      # The name of the default postgres database.
      POSTGRES_DB: fss
      # postgres data directory
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./volumes/db/data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  # The redis cache.
  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      # Mount the redis data directory to the container.
      - ./volumes/redis/data:/data
    # Set the redis password when startup redis server.
    command: redis-server --requirepass fss123#456
    ports:
      - "6379:6379"

  # The Fss server
  fss_server:
    container_name: fss_server
    image: tyvek2zhang/fastapi-sqlmodel-starter:v1.0.0
    restart: always
    command: "sh -c 'cd fss && alembic upgrade head && python apiserver.py'"
    depends_on:
      - db
      - redis
    ports:
      - 9010:9010
    volumes:
      - ./volumes/app/log:/app/log
