version: '3.8'

services:
  fast_web_server:
    container_name: fast_web_server
    image: tyvek2zhang/fast-web:2.0.0
    restart: always
    command: "sh -c 'uv run alembic upgrade head && uv run apiserver.py'"
    ports:
      - 9010:9010
