version: '3.8'

services:
  fast_web_server:
    container_name: fast_web_server
    image: tyvek2zhang/fast-web:1.1.1
    restart: always
    command: "sh -c 'cd src && alembic upgrade head && python apiserver.py'"
    ports:
      - 9010:9010
