---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: src-server-deployment
  labels:
    app: src-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: src-server
  template:
    metadata:
      labels:
        app: src-server
    spec:
      containers:
      - name: src-server
        image: tyvek2zhang/fast-web:v1.1.1
        command: ["sh", "-c", "cd src && alembic upgrade head && python apiserver.py"]
        ports:
        - containerPort: 9010
