server:
  name: Fast web
  host: 127.0.0.1
  workers: 1
  debug: True
  log_file_path: ./log/fast_web.log

database:
  url: sqlite+aiosqlite:///src/main/resource/alembic/db/fast_web.db

security:
  enable: True
  enable_swagger: True
