name: Welcome New Contributors

on:
  issues:
    types: [opened]
  pull_request:
    types: [opened]

jobs:
  welcome:
    runs-on: ubuntu-latest
    steps:
    - name: Welcome
      uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: '感谢你开启第一个 issue！请确保你已经阅读我们的 CONTRIBUTING.md 文件，如果你有任何问题，随时在这里提问。'
        pr-message: '非常感谢你的 pull request！请确保你的代码符合我们的代码规范，并已经添加了必要的测试。'
